post_install() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
  gtk4-update-icon-cache -qtf /usr/share/icons/hicolor
  update-desktop-database -q /usr/share/applications
}

post_upgrade() {
  post_install
}

post_remove() {
  glib-compile-schemas /usr/share/glib-2.0/schemas >/dev/null 2>&1 || true
  gtk4-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true
  update-desktop-database -q /usr/share/applications 2>/dev/null || true
}
